version: '3.3'

services:
  python-app:
    build: ./web_app
    container_name: python-app
    ports:
      - 5000:5000
    depends_on:
      - postgres-finaltask
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    # command: sh -c "
    #   sleep 5 &&
    #   python3 -m gunicorn -w 1 app:app -b 0.0.0.0:5000"

  postgres-finaltask:
    image: postgres:latest
    container_name: postgres-finaltask
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./web_app/pginit:/docker-entrypoint-initdb.d/